# Generated by Django 3.2.9 on 2021-11-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='disponible',
            field=models.CharField(max_length=50),
        ),
    ]
